events {}

http {
    log_format main
    '$remote_addr - $host "$request" '
    'status=$status '
    'request_time=$request_time '
    'upstream_response_time=$upstream_response_time '
    'upstream_status=$upstream_status '
    'request_id=$request_id';

    access_log /var/log/nginx/access.log main;

    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=5r/m;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        add_header X-Request-ID $request_id always;
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

        client_max_body_size 20M;

        proxy_connect_timeout 5s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;

        location = /healthz {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Request-ID $request_id;

            proxy_pass http://api:80;
        }

        location /v1/auth/token {
            limit_req zone=auth_limit burst=2 nodelay;
            # limit_req_status 429;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Request-ID $request_id;

            proxy_pass http://api:80;
        }

        location ^~ /static/ {
            try_files $uri =404;
        }

        location ~* \.(jpg|jpeg|png|gif)$ {
            try_files $uri =404;
        }

        location /v1/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Request-ID $request_id;

            proxy_pass http://api:80;
        }

        location /docs {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Request-ID $request_id;

            proxy_pass http://api:80;
        }
        location = /openapi.json {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Request-ID $request_id;

        proxy_pass http://api:80;
        }   
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}