"""add scan priority

Revision ID: 399f4c548bbf
Revises: 961646961cc6
Create Date: 2026-09-14 03:07:01.282223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '399f4c548bbf'
down_revision: Union[str, Sequence[str], None] = '961646961cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('priority', sa.TEXT(), server_default=sa.text("'normal'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'priority')
    # ### end Alembic commands ###
