"""add analysis jobs

Revision ID: 45b3d2213c41
Revises: 961646961cc6
Create Date: 2026-09-24 04:07:11.025517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b3d2213c41'
down_revision: Union[str, Sequence[str], None] = '961646961cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('findings', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed')", name='analysis_jobs_status_check'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_jobs_status_created_at', 'analysis_jobs', ['status', 'created_at'], unique=False)
    op.drop_table('injection_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injection_test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body_part', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index('idx_analysis_jobs_status_created_at', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
