"""initial schema

Revision ID: 961646961cc6
Revises: 
Create Date: 2026-09-14 03:05:14.319021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961646961cc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('synthetic_study_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sex', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sex IN ('male', 'female', 'other')", name='patients_sex_check'),
    sa.PrimaryKeyConstraint('synthetic_study_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('hashed_password', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('clinician', 'radiologist', 'admin')", name='users_role_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.TEXT(), nullable=False),
    sa.Column('entity', sa.TEXT(), nullable=False),
    sa.Column('entity_id', sa.TEXT(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('modality', sa.TEXT(), nullable=False),
    sa.Column('body_part', sa.TEXT(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("modality IN ('CT', 'MRI', 'X-ray')", name='scans_modality_check'),
    sa.CheckConstraint("status IN ('uploaded', 'processing', 'completed', 'failed')", name='scans_status_check'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.synthetic_study_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scans_acquired_at', 'scans', ['acquired_at'], unique=False)
    op.create_index('idx_scans_modality_acquired_at', 'scans', ['modality', 'acquired_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('findings', sa.TEXT(), nullable=False),
    sa.Column('radiologist_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['radiologist_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index('idx_scans_modality_acquired_at', table_name='scans')
    op.drop_index('idx_scans_acquired_at', table_name='scans')
    op.drop_table('scans')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
