"""add scan file and report pdf keys

Revision ID: a69643694ceb
Revises: c6e92c719978
Create Date: 2026-10-03 20:44:53.474521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69643694ceb'
down_revision: Union[str, Sequence[str], None] = 'c6e92c719978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debug_lock_test')
    op.add_column('reports', sa.Column('pdf_key', sa.TEXT(), nullable=True))
    op.add_column('scans', sa.Column('file_key', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'file_key')
    op.drop_column('reports', 'pdf_key')
    op.create_table('debug_lock_test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('debug_lock_test_pkey'))
    )
    # ### end Alembic commands ###
